add_newline = true
format = """ 
$username\
$time\
$kubernetes\
$gcloud\
$git_branch\
$git_commit\
$git_state\
$git_status\
$python\
$rust\
$pulumi\
$cmd_duration\
$line_break\
$jobs\
$directory\
$shell\
$status\
$character
"""

[directory]
truncation_length = 4 
truncate_to_repo = false
truncation_symbol = "â€¦/"
style = "white"

[gcloud]
format = "[$symbol$active]($style) "
symbol = " "
style = "bright-green"

[git_branch]
format = "[$symbol$branch]($style) "
symbol = " "

[git_commit]
only_detached=false
style='green'
format='[\[$hash$tag\]]($style) '

[kubernetes]
format = "[$symbol$context\\($namespace\\)]($style) "
style = "bright-blue"
disabled = false
[kubernetes.context_aliases]
"gke_.*_(?P<var_cluster>[\\w-]+)" = "$var_cluster"

[pulumi]
format = "[$symbol$stack]($style) "

[python]
format = "[$symbol$version]($style) "
disabled = false

[shlvl]
threshold = 1 
disabled = false

[time]
format = "[ðŸ•’ $time]($style) "
style = "yellow"
disabled = false 